#!/bin/bash

if [ ! -d ./trace ]
    then
        echo "./trace does not exist, creating it"
        mkdir trace > /dev/null
fi
env python -m trace -tcg -C trace ./exactCover.py > ./trace/exactCover.trace