#!/bin/bash

if [ ! -d ./trace ]
    then
        mkdir ./trace > /dev/null
fi
env python -m trace -tcg -C trace ./exactCover.py > ./trace/exactCover.cover
sed 's/\(\w\)\+\.\(\w\)\+ \(\w\)\+\.py(\(\w\)\+):/"&"/' <./trace/exactCover.cover >./trace/exactCover.py
find . -name '*.cover' -print0 | xargs -0 rm
